name: Monthly Retrain

on:
  schedule:
    # Runs at 00:00 on the 1st day of each month
    - cron: "0 0 1 * *"

  # (Optional) Allow manual trigger too
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Hit retrain API endpoint
        run: |
          curl -X 'POST' \
          'https://mk12rule-air-quality-api.hf.space/retrain' \
          -H 'accept: application/json' \
          -d ''
